Repository hyewon-han/baple, pull requests merged in 2024-02, with the labels that each got.

#183 ]Feat/responsive] 댓글 실시간 알림 추가
  public/images/icons/button/prev.svg
  src/apis/boards.ts
  src/apis/commentAlarm.ts
  src/apis/commentAlert.ts
  src/components/board/Editor.tsx
  src/components/common/AlarmModal.tsx
  src/components/home/MostReviews.tsx
  src/components/layout/Header.tsx
  src/components/place_detail/PlaceDetailHeader.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewLikes.tsx
  src/hooks/useAlarm.ts
  src/pages/board/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/types/supabase.d.ts
  src/utils/dateFormatter.ts
Labels: 🎉add, 💄 style, ✨ update

#184 [Feat/places] 메인페이지에 필터링 버튼 8개 추가 및 장소검색페이지 버튼들 고정
  public/images/icons/place_detail_icons/운영시간.svg
  public/images/icons/place_detail_icons/전화번호.svg
  public/images/icons/place_detail_icons/주소.svg
  public/images/icons/place_detail_icons/홈페이지.svg
  public/images/icons/place_detail_icons/홈페이지2.svg
  public/images/icons/place_detail_icons/휴무일.svg
  src/apis/places.ts
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/pages/review/write/[placeId]/index.tsx
  src/redux/config/configStore.ts
  src/redux/modules/searchSlice.ts
  src/redux/modules/seletedBtnSlice.ts
Labels: 🎉add, 💄 style, ✨ update

#185 [Refactor/code] Quill 에디터 도입
  package.json
  src/components/board/Editor.tsx
  src/components/common/QuillEditor.tsx
  src/components/common/SpinnerModal.tsx
  src/components/common/TuiEditor.tsx
  src/components/common/TuiViewer.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/write/[placeId]/index.tsx
  src/styles/globals.css
  src/utils/dateFormatter.ts
  yarn.lock
Labels: 🎉add, ♻️ refactor, 🔨 script, 💄 style

#186 update : 모두 읽음 버튼 조건부 처리(#104)
  src/components/common/AlarmModal.tsx
  src/components/layout/Header.tsx
Labels: 🩹 fix

#189 [Feat/places] 헤더 프로필이미지 드롭다운 -> 팝오버로 수정
  public/images/avatar_default.jpg
  public/images/baple_logo.png
  public/images/mainCarousel1.svg
  public/images/mainCarousel2.svg
  src/components/common/Carousel.tsx
  src/components/layout/Header.tsx
  src/components/layout/Seo.tsx
  src/pages/index.tsx
  src/pages/nearby/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/user/index.tsx
  src/styles/globals.css
  src/utils/dateFormatter.ts
  tailwind.config.ts
Labels: 🐛 bugfix, 🚚 move, 💄 style

#190 ]Feat/responsive] 좋아요 알림 추가
  src/apis/alarms.ts
  src/components/common/AlarmModal.tsx
  src/components/layout/Header.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewLikes.tsx
  src/hooks/useAlarm.ts
  src/hooks/useLikes.ts
  src/pages/review/[reviewId]/index.tsx
  src/types/supabase.d.ts
Labels: 🎉add, 🩹 fix, 💄 style, ✨ update

#191 [Refactor/code] board 게시글에 사진이 있을시 게시글이 삭제될때 함께 삭제
  src/apis/boards.ts
  src/components/board/Editor.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentCardMobile.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/board/[boardId]/index.tsx
Labels: 🩹 fix, ♻️ refactor, 💄 style

#193 [Feat/places] 장소검색페이지 에서 스크롤 내린 후 장소상세 갔다가 다시 돌어와도 스크롤 위치 고정
  package.json
  src/apis/places.ts
  src/components/common/AlarmModal.tsx
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard2.tsx
  src/components/layout/Header.tsx
  src/components/places/SkeletonCard.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
  yarn.lock
Labels: 🐛 bugfix, 🎉add, ✨ update

#194 [Refactor/code] boards 페이지 ISR , 코드정리
  src/apis/boards.ts
  src/components/common/PlaceCard2.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/map/MarkerContainer.tsx
  src/components/mypage/MyTabs.tsx
  src/pages/board/index.tsx
  src/pages/index.tsx
  src/types/types.d.ts
Labels: 🩹 fix, ♻️ refactor

#195 [Feat/responsive]
  public/images/icons/button/next.svg
  public/images/icons/button/next_blind.svg
  public/images/icons/button/prev.svg
  public/images/icons/button/prev_blind.svg
  src/components/common/AlarmModal.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/styles/globals.css
Labels: 💄 style

#198 [Refactor/code] _error.tsx 생성, 동적 라우팅에서 이상한 경로로 진입했을 경우에 대한 에러 핸들링 및 SSR, ISR
  src/components/board/Editor.tsx
  src/pages/_error.tsx
  src/pages/board/[boardId].tsx
  src/pages/board/index.tsx
  src/pages/review/[reviewId]/index.tsx
Labels: 🎉add, 🩹 fix, ♻️ refactor, 💄 style

#199 [Feat/responsive] 코드 리팩토링(컴포넌트화 & 커스텀훅)
  src/components/layout/Header.tsx
  src/components/place_details/PaiginatedReviews.tsx
  src/components/place_details/PlaceDetailInfo.tsx
  src/components/place_details/PlaceDetailInfoHeader.tsx
  src/components/place_details/PlaceDetailMap.tsx
  src/components/place_details/PlaceDetailReview.tsx
  src/hooks/useAlarmSubscribe.ts
  src/hooks/useAlarmSubscribeComment.ts
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
Labels: 🩹 fix, ♻️ refactor

#200 [Feat/places] 장소검색 city로 가능하게 수정
  src/apis/places.ts
  src/components/common/AlarmModal.tsx
  src/components/common/PlaceCard.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/layout/SideBar.tsx
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/redux/config/configStore.ts
  src/redux/modules/selectedCitySlice.ts
  src/redux/modules/seletedBtnSlice.ts
  src/types/types.d.ts
  src/utils/defaultValue.ts
Labels: 🎉add, 💄 style, ✨ update

#202 Feat/about page 기본구조 완성 디테일 수정 필요
  public/images/aboutPage/Carousel1.png
  public/images/aboutPage/Carousel2.png
  public/images/aboutPage/Carousel3.png
  public/images/aboutPage/Carousel4.png
  public/images/aboutPage/Carousel5.png
  public/images/aboutPage/Group 1181.png
  public/images/aboutPage/LastSection.png
  public/images/aboutPage/MacBook Pro 23.png
  public/images/aboutPage/about_LOGO.png
  public/images/aboutPage/iPhone 15.png
  src/components/about/Youtube.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/PlacesModal.tsx
  src/components/place_details/PlaceDetailMap.tsx
  src/pages/about/index.tsx
  src/pages/nearby/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎉add, 💄 style

#203 ]Feat/responsive] 리팩토링 및 어바웃 페이지 수정
  public/images/aboutPage/MacBookPro23.png
  public/images/aboutPage/lastSectionImg.png
  src/apis/alarms.ts
  src/apis/bookmarks.ts
  src/apis/likes.ts
  src/components/place_details/PlaceDetailInfo.tsx
  src/components/place_details/PlaceDetailInfoBody.tsx
  src/components/place_details/PlaceDetailInfoFooter.tsx
  src/components/place_details/PlaceDetailInfoHeader.tsx
  src/components/review_details/ReviewLikes.tsx
  src/hooks/useBookmarks.ts
  src/hooks/useLikes.ts
  src/pages/about/index.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🩹 fix

#204 Feat/about page 안쓰는 이미지 삭제,컴포넌트 이름변경,유튜브 화면 반응형 사이즈로 조절
  public/images/aboutPage/Group 1181.png
  public/images/aboutPage/LastSection.png
  public/images/aboutPage/iPhone 15.png
  src/components/about/YoutubeCard.tsx
  src/pages/about/index.tsx
Labels: 🔥 del, 🩹 fix

#206 [Refactor/code]
  src/components/board/BoardTable.tsx
  src/components/board/Editor.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/MarkerPlaceCard.tsx
  src/pages/_error.tsx
  src/pages/board/index.tsx
  src/pages/index.tsx
  src/pages/places/index.tsx
Labels: 🚚 move, ♻️ refactor

#207 Feat/about page aboutPage 첫 섹션 line-height조절
  src/pages/about/index.tsx
Labels: 💄 style

#208 [Feat/places] 디폴트이미지 수정 및 메인캐러셀이미지 수정
  public/images/default.png
  public/images/default2.png
  public/images/default2_blue.png
  public/images/default3.png
  public/images/default3_blue.png
  public/images/default_blue.png
  public/images/mainCarousel1.png
  public/images/mainCarousel1.svg
  public/images/mainCarousel2.png
  public/images/mainCarousel2.svg
  public/images/mainCarousel3.png
  public/images/mobile_banner1.png
  public/images/mobile_banner2.png
  public/images/mobile_banner3.png
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/map/MarkerPlaceCard.tsx
  src/pages/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/utils/defaultValue.ts
Labels: 🎉add, 💄 style

#209 ]Feat/responsive] 장소상세 아이콘 수정 & 장소카드 스타일 수정
  public/images/icons/place_detail_icons/운영시간.svg
  public/images/icons/place_detail_icons/전화번호.svg
  public/images/icons/place_detail_icons/주소.svg
  public/images/icons/place_detail_icons/주소_색약모드.svg
  public/images/icons/place_detail_icons/홈페이지.svg
  public/images/icons/place_detail_icons/홈페이지2.svg
  public/images/icons/place_detail_icons/휴무일.svg
  src/components/common/PlaceCard.tsx
  src/components/layout/Header.tsx
  src/components/map/MarkerPlaceCard.tsx
  src/components/place_details/PlaceDetailInfoBody.tsx
  src/hooks/useAlarmSubscribe.ts
  src/styles/globals.css
Labels: 🩹 fix, 💄 style

#211 [Feat/responsive] 자잘한 코드수정 및 리팩토링
  next.config.js
  public/images/icons/CBicons/CBbookmark_select.svg
  public/images/icons/CBicons/CBbookmark_select_.svg
  src/apis/boards.ts
  src/apis/comments.ts
  src/apis/likes.ts
  src/apis/places.ts
  src/apis/reviews.ts
  src/components/board/BoardTable.tsx
  src/components/common/Carousel.tsx
  src/components/common/Carousel_Thumb.tsx
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/layout/Header.tsx
  src/components/map/MarkerPlaceCard.tsx
  src/components/place_details/PaiginatedReviews.tsx
  src/components/place_details/PlaceDetailInfoBody.tsx
  src/components/place_details/PlaceDetailInfoFooter.tsx
  src/components/place_details/PlaceDetailInfoHeader.tsx
  src/components/place_details/PlaceDetailMap.tsx
  src/components/place_details/PlaceDetailReview.tsx
  src/components/review_details/ReviewBody.tsx
  src/hooks/useBookmarks.ts
  src/pages/about/index.tsx
  src/pages/login/index.tsx
  src/pages/nearby/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/redux/config/configStore.ts
  src/redux/modules/authSlice.ts
Labels: 🩹 fix, ♻️ refactor

#212 [Refactor/final] readme 뼈대 작성, 리팩토링
  README.md
  src/pages/board/index.tsx
Labels: 🎉add, ♻️ refactor

#214 Feat/about page 주석제거,state사용 부분 useSelector교체
  src/components/map/MarkerContainer.tsx
  src/components/map/MarkerPlaceCard.tsx
  src/components/place_details/PlaceDetailMap.tsx
  src/pages/nearby/index.tsx
Labels: ♻️ refactor

#215 [Feat/places] 로그아웃 상태일 때 리뷰 작성 못하도록 수정
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentCardMobile.tsx
  src/pages/about/index.tsx
  src/pages/review/write/[placeId]/index.tsx
Labels: 🐛 bugfix

#216 [Refactor/final] readme 수정
  README.md
  public/images/service-architecture.png
  src/pages/board/[boardId].tsx
  src/pages/providers.tsx
Labels: ♻️ refactor

#218 [update : readme 수정]
  README.md
Labels: 🩹 fix

#219 [refactor/final] import 정리, 주석정리
  src/components/common/AlarmModal.tsx
  src/components/common/Carousel_Thumb.tsx
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ReviewCardMobile.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/components/layout/ThemeSwitcher.tsx
  src/components/mypage/MyProfile.tsx
  src/components/mypage/MyTabs.tsx
  src/components/place_details/PaiginatedReviews.tsx
  src/components/place_details/PlaceDetailInfo.tsx
  src/components/place_details/PlaceDetailInfoBody.tsx
  src/components/place_details/PlaceDetailInfoFooter.tsx
  src/components/place_details/PlaceDetailMap.tsx
  src/components/place_details/PlaceDetailReview.tsx
  src/components/places/SkeletonCard.tsx
  src/hooks/useReviews.ts
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/board/index.tsx
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/pages/signup/index.tsx
  src/pages/update-password/index.tsx
  src/styles/globals.css
  src/utils/newComment.ts
  src/utils/shareKaKao.ts
Labels: ♻️ refactor

#221 [refactor/final] kakao share 이미지 수정
  src/utils/shareKaKao.ts
Labels: 🩹 fix

#223 [Feat/places]
  src/components/common/PlaceCard.tsx
  src/hooks/useBookmarks.ts
  src/hooks/useReviews.ts
Labels: 🐛 bugfix

#233 bugfix : 실시간 알림 오작동 수정(#197)
  src/components/common/Carousel_Thumb.tsx
  src/components/common/PlaceCard3.tsx
  src/hooks/useAlarmSubscribe.ts
Labels: 🐛 bugfix
