Repository hyewon-han/baple, pull requests merged in 2024-01, with the labels that each got.

#8 지도 연결완료
  package.json
  src/components/map/KakaoMap.tsx
  src/pages/_document.tsx
  src/pages/nearby/index.tsx
  tsconfig.json
Labels: 🎉add

#9 Feat/review detail
  next.config.js
  src/apis/comments.ts
  src/apis/reviews.ts
  src/components/Layout.tsx
  src/components/layout/MainWrapper.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/CommentList.tsx
  src/components/review_details/ReviewBody.tsx
  src/pages/providers.tsx
  src/pages/review/[reviewId]/index.tsx
  src/utils/dateFormatter.ts
Labels: 🎉add

#11 Feat/review detail
  next.config.js
  package.json
  src/apis/comments.ts
  src/apis/reviews.ts
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/pages/providers.tsx
  src/pages/review/[reviewId]/index.tsx
  src/utils/newComment.ts
  yarn.lock
Labels: 🎉add

#12 Feat/place detail
  package.json
  src/api/places.ts
  src/apis/places.ts
  src/apis/reviews.ts
  src/components/common/Carousel.tsx
  src/components/layout/Header.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/pages/place/[placeId]/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: 🎉add

#15 Feat/map nearby페이지 맵 기본기능 구현
  package.json
  src/components/map/KakaoMap.tsx
  src/pages/nearby/index.tsx
  yarn.lock
Labels: 🎉add

#19 Feat/review detail
  package.json
  src/apis/comments.ts
  src/apis/reviews.ts
  src/components/common/TuiEditor.tsx
  src/components/common/TuiViewer.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewBody.tsx
  src/constants/temp_develop.ts
  src/pages/place/[placeId]/index.tsx
  src/pages/providers.tsx
  src/pages/review/[reviewId]/index.tsx
  src/types/supabase.d.ts
  src/types/types.d.ts
  src/utils/dateFormatter.ts
  tailwind.config.ts
  yarn.lock
Labels: 🎉add, ♻️ refactor, 🔨 script, ✨ update

#20 Feat/map nearby페이지 지도 기본기능 구현 완료
  src/components/overlaymap/MarkerContainer.tsx
  src/pages/nearby/index.tsx
  src/types/supabase.d.ts
Labels: 🎉add

#23 [Feat/auth] 회원정보 수정 기능 구현
  package.json
  src/apis/users.ts
  src/components/layout/Header.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/pages/user/[userId]/index.tsx
  src/redux/modules/authSlice.ts
  yarn.lock
Labels: 🐛 bugfix, ✨ update

#25 Feat/map 현재위치 버튼 추가
  src/components/layout/Header.tsx
  src/components/overlaymap/MylocationButton.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/pages/nearby/index.tsx
  src/styles/globals.css
Labels: 🎉add

#27 Feat/place detail
  src/apis/bookmark.ts
  src/components/place_detail/PlaceDetail.tsx
Labels: 🐛 bugfix, 🩹 fix

#31 [Feat/auth] 카카오 로그인 기능 구현 및 아바타만 수정시 닉네임 지워지는 오류 수정
  public/images/kakao_login.png
  src/apis/comments.ts
  src/apis/reviews.ts
  src/apis/users.ts
  src/components/layout/Header.tsx
  src/components/review_details/CommentCard.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/nearby/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/pages/review/write/[placeId]/index.tsx
  src/pages/signup/index.tsx
  src/pages/user/[userId]/index.tsx
  src/redux/modules/authSlice.ts
  src/types/supabase.d.ts
  src/types/types.d.ts
Labels: 🐛 bugfix, 💄 style, ✨ update

#36 Feat/place detail
  src/apis/bookmarks.ts
  src/apis/likes.ts
  src/apis/places.ts
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/_app.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/types/supabase.d.ts
  tailwind.config.ts
Labels: 🎉add

#42 refactor : ReviewCard.tsx 확장성있게 수정 (#32)
  src/apis/users.ts
  src/components/common/ReviewCard.tsx
  src/pages/review/write/[placeId]/index.tsx
Labels: ♻️ refactor

#43 Feat/place detail
  next.config.js
  src/components/common/Carousel.tsx
  src/components/common/PlaceCard.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/styles/globals.css
  src/types/supabase.d.ts
  src/utils/shareKaKao.ts
Labels: 🎉add, 🚚 move, 💄 style

#47 Feat/map 페이지 모달추가&모달에 현위치,장소목록추가,페이지네이션추가
  src/components/map/MapPlaceCard.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/MylocationButton.tsx
  src/components/map/PagiNation.tsx
  src/components/map/PlacesModal.tsx
  src/components/overlaymap/MylocationButton.tsx
  src/pages/nearby/index.tsx
  src/redux/config/configStore.ts
  src/redux/modules/placesDataSlice.ts
Labels: 🎉add, 🩹 fix

#49 feat:상세페이지 지도 구현완료(#3)
  src/components/place_detail/PlaceDetail.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🎉add

#50 새 리뷰 입력 오류 수정
  src/pages/review/write/[placeId]/index.tsx
Labels: 🐛 bugfix

#51 [Feat/places] 리뷰 등록 시 이미지 파일 있으면 장소 대표이미지 등록 / 장소 검색 페이지 무한스크롤 구현
  package.json
  src/apis/places.ts
  src/components/common/PlaceCard2.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyTabs.tsx
  src/pages/places/index.tsx
  src/pages/review/write/[placeId]/index.tsx
  yarn.lock
Labels: 🎉add, 🔥 del, 🔨 script, ✨ update

#53 [feat/review_update] 리뷰 수정창에서 에디터 제거-> textarea 로 대체 (#52)
  src/components/review_details/ReviewBody.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/review/[reviewId]/index.tsx
Labels: 🩹 fix

#57 Feat/place detail
  src/components/common/Carousel.tsx
  src/components/common/Carousel_Thumb.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/styles/globals.css
Labels: 💄 style

#58 Feat/place category filter
  src/components/map/MapPlaceCard.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/PagiNation.tsx
  src/components/map/PlacesModal.tsx
  src/pages/nearby/index.tsx
  src/pages/places/index.tsx
Labels: 🎉add, ♻️ refactor

#61 [review_detail_design] 리뷰 디테일 페이지 새 디자인에 맞춰 styling (#59)
  src/components/common/ReviewCard2.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/CommentList.tsx
  src/components/review_details/ReviewBody.tsx
  src/components/review_details/ReviewLikes.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/utils/dateFormatter.ts
  tailwind.config.ts
Labels: ♻️ refactor, 💄 style

#64 Feat/board
  src/apis/boards.ts
  src/components/layout/Header.tsx
  src/components/map/MapPlaceCard.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/pages/board/write/index.tsx
  src/pages/index.tsx
  src/redux/config/configStore.ts
  src/redux/modules/authSlice.ts
  src/redux/modules/placesDataSlice.ts
  src/types/supabase.d.ts
Labels: 🎉add, ✨ update

#65 Feat/place category filter 검색 필터링 부분 수정했습니다
  src/pages/_app.tsx
  src/pages/nearby/index.tsx
  src/pages/places/index.tsx
Labels: 🩹 fix

#71 Feat/place category filter places페이지 체크박스 버튼으로 교체 & 약간의 스타일 수정
  src/components/common/PlaceCard2.tsx
  src/pages/places/index.tsx
Labels: 🩹 fix, ♻️ refactor, 💄 style

#78 [feat/update_delete_restriction] 글쓴이만 자기 글/댓글 수정/삭제 가능하도록 제한 (#73)
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/review/[reviewId]/index.tsx
  src/types/types.d.ts
Labels: 🎉add, 🩹 fix

#80 Feat/place category filter place페이지 레이아웃 살~짝 수정
  src/pages/places/index.tsx
Labels: 🩹 fix

#81 Feat/board
  src/components/common/Carousel.tsx
  src/components/common/Carousel_Thumb.tsx
  src/components/common/PlaceCard.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewBody.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/board/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
  tailwind.config.ts
Labels: ♻️ refactor, 💄 style

#84 style : 일부 아이콘 추가, 헤더에 로고 삽입
  src/components/common/ReviewCard2.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
Labels: 💄 style

#85 Feat/place category filter svg마커 추가
  next.config.js
  package.json
  src/components/map/MapPlaceCard.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/MylocationButton.tsx
  src/components/map/MylocationOverlayMap.tsx
  src/components/map/PlacesModal.tsx
  src/pages/nearby/index.tsx
  src/types/types.d.ts
  yarn.lock
Labels: 💄 style

#87 [Feat/places] 회원가입 및 로그인 시 초기 렌더링 오류 수정
  src/components/layout/Header.tsx
  src/components/mypage/MyProfile.tsx
  src/pages/signup/index.tsx
Labels: 🐛 bugfix

#88 Feat/board
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/board/index.tsx
  src/pages/board/write/index.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🐛 bugfix, 💄 style, ✨ update

#89 fix : toast 수정
  src/components/place_detail/PlaceDetail.tsx
Labels: 🩹 fix

#91 bugfix : 리뷰 삭제 컨펌창만 떠도 삭제되는 오류 해결 (#44)
  src/components/review_details/ReviewUpperSection.tsx
Labels: 🐛 bugfix

#93 fix:지도 현재위치 아닐때 스피너처리, 마커색상변경
  next.config.js
  public/images/icons/marker.svg
  src/components/map/PlacesModal.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/nearby/index.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🩹 fix, 💄 style

#94 Feat/board 게시글 삭제 기능 추가
  src/apis/boards.ts
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/pages/board/write/index.tsx
Labels: 🐛 bugfix, 🩹 fix, ✨ update

#97 Feat/board
  src/apis/boards.ts
  src/components/board/Editor.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/write/index.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🎉add, ♻️ refactor, ✨ update

#98 [Feat/places] 댓글 수정 기능 추가 및 useComment 커스텀 훅으로 분리
  src/apis/bookmarks.ts
  src/apis/comments.ts
  src/apis/users.ts
  src/components/mypage/MyProfile.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/hooks/useComments.ts
  src/pages/404.tsx
  src/pages/review/[reviewId]/index.tsx
  src/pages/signup/index.tsx
  src/types/supabase.d.ts
  src/utils/newComment.ts
  src/utils/validationUtils.ts
Labels: 🐛 bugfix, 🎉add, 🩹 fix, 🚚 move, ♻️ refactor, ✨ update

#99 [fix/review] 디버깅 + 리팩토링 + 스타일링 (#95)
  src/apis/comments.ts
  src/components/common/ReviewCard2.tsx
  src/components/layout/MainWrapper.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/CommentList.tsx
  src/components/review_details/ReviewLikes.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/types/types.d.ts
  tailwind.config.ts
Labels: 🩹 fix, 💄 style

#100 Feat/map eslint에러 문제 해결 & 지도 appkey 리다이렉트
  .eslintrc.json
  next.config.js
  src/components/map/PlacesModal.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/nearby/index.tsx
  src/pages/places/index.tsx
Labels: 🐛 bugfix, 🩹 fix

#103 [fix/review] 디버깅 + 리팩토링 + 스타일링 (#95)
  src/apis/places.ts
  src/components/common/PlaceCard.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/mypage/MyTabs.tsx
  src/types/types.d.ts
Labels: ♻️ refactor

#105 Feat/board
  src/components/board/Editor.tsx
  src/components/layout/MainWrapper.tsx
  src/components/layout/Seo.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewLikes.tsx
  src/hooks/useBoards.ts
  src/hooks/useBookmarks.ts
  src/hooks/useLikes.ts
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/pages/board/write/index.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🎉add, 🩹 fix, ♻️ refactor, 💄 style

#106 [fix/review] 디버깅 + 리팩토링 + 스타일링 (#95)
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/review_details/ReviewBody.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/hooks/useReviews.ts
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/pages/review/write/[placeId]/index.tsx
  src/types/types.d.ts
Labels: 🎉add, 🩹 fix, ♻️ refactor

#107 [Feat/places] 헤더 반응형 구현
  src/components/Layout.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/components/mypage/MyTabs.tsx
  src/constants/temp_develop.ts
  src/pages/login/index.tsx
  src/pages/nearby/index.tsx
  src/pages/signup/index.tsx
Labels: 🐛 bugfix, 🎉add, 🔥 del, 💄 style, ✨ update

#108 [Feat/places] 장소카드 수정 홈 반응형 약간 구현
  package.json
  public/images/icons/bookmark.svg
  public/images/icons/bookmark_select.svg
  public/images/icons/cancel.svg
  public/images/icons/cancel_select.svg
  public/images/icons/comment.svg
  public/images/icons/comment_select.svg
  public/images/icons/heart.svg
  public/images/icons/heart_select.svg
  public/images/icons/image.svg
  public/images/icons/image_select.svg
  public/images/icons/search.svg
  public/images/icons/search_select.svg
  public/images/icons/share.svg
  public/images/icons/share_select.svg
  public/images/icons/write.svg
  public/images/icons/write_select.svg
  src/components/board/Editor.tsx
  src/components/common/PlaceCard.tsx
  src/components/common/ReviewCard2.tsx
  src/components/common/TopButton.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyTabs.tsx
  src/components/review_details/CommentCard.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/hooks/useMobile.ts
  src/hooks/useReviews.ts
  src/pages/board/[boardId]/index.tsx
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: 🎉add, 💄 style

#109 [Fix/review] 반응형 디자인 WIP (#95)
  src/components/common/ReviewCard2.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/review_details/ReviewBody.tsx
  src/hooks/useBookmarks.ts
  src/hooks/useViewport.ts
  src/pages/review/[reviewId]/index.tsx
  tailwind.config.ts
Labels: 💄 style

#111 [Feat/places] 장소 검색 페이지 & 메인 페이지 반응형 구현 (미완)
  src/components/common/PlaceCard.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/layout/Header.tsx
  src/pages/places/index.tsx
Labels: 💄 style

#113 hotfix : 오류 수정(#95)
  src/components/mypage/MyTabs.tsx
Labels: 🐛 bugfix

#114 Feat/board
  public/images/icons/empty-heart.svg
  public/images/icons/filled-heart.svg
  src/components/board/Editor.tsx
  src/components/common/Carousel_Thumb.tsx
  src/components/common/PlaceCard.tsx
  src/components/home/MostReviews.tsx
  src/components/layout/Header.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/place_detail/PlaceDetailHeader.tsx
  src/components/review_details/ReviewLikes.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/pages/board/write/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
Labels: 🎉add, ♻️ refactor, 💄 style

#115 style : 장소카드 이미지 선명하게 수정 (#101)
  src/components/common/PlaceCard.tsx
  src/components/common/ReviewCardMobile.tsx
  src/pages/nearby/index.tsx
Labels: 💄 style

#117 [feat/places] 홈 화면 디자인 수정
  src/components/common/Carousel.tsx
  src/components/common/TopButton.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
  src/pages/nearby/index.tsx
  src/pages/places/index.tsx
Labels: 🐛 bugfix, 💄 style

#118 style : safelist에 h-[400px] 추가 (#101)
  src/components/common/Carousel.tsx
  tailwind.config.ts
Labels: 🐛 bugfix

#119 Feat/map nearby페이지 반응형 추가
  src/components/layout/Header.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/MylocationOverlayMap.tsx
  src/components/map/PagiNation.tsx
  src/components/map/PlacesModal.tsx
  src/pages/nearby/index.tsx
  src/pages/place/[placeId]/index.tsx
  tailwind.config.ts
Labels: 🎉add, ♻️ refactor, 💄 style

#123 [Fix/review] 모바일 버전 프로필 소세지 문제 해결
  src/components/review_details/ReviewUpperSection.tsx
Labels: 💄 style

#125 fix:nearby페이지 모바일 접속시 살짝 깨지는 문제 & 카드에서 글자 넘침 해결
  src/components/map/MapPlaceCard.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/PagiNation.tsx
  src/components/map/PlacesModal.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🩹 fix

#126 [Feat/places] 장소카드3 추가 및 마이페이지 반응형 구현 (almost)
  public/images/icons/bookmark_select_.svg
  public/images/icons/search.svg
  public/images/icons/search_white.svg
  src/apis/places.ts
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/mypage/MyProfile.tsx
  src/components/mypage/MyTabs.tsx
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/utils/dateFormatter.ts
Labels: 🎉add, 💄 style

#129 Feat/main page search nearby페이지 버튼 위치 수정
  src/components/map/PagiNation.tsx
  src/components/map/PlacesModal.tsx
Labels: 💄 style

#130 [Feat/additional] 추가 theme 토글 추가, css 스타일링, minor 코드 수정
  src/components/common/ReviewCard2.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainWrapper.tsx
  src/components/layout/ThemeSwitcher.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/providers.tsx
  tailwind.config.ts
Labels: 🎉add

#131 [Feat/places] 로고 변경 및 로그인 회원가입 반응형 구현
  public/images/icons/basic-logo.svg
  src/components/common/ReviewCard.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyTabs.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/pages/login/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/pages/signup/index.tsx
  src/pages/user/[userId]/index.tsx
  src/utils/validationUtils.ts
Labels: 🎉add, 💄 style, ✨ update

#134 [feat/main_search] 메인페이지에서 검색 기능 작동시키기(#133)
  src/pages/index.tsx
  src/pages/places/index.tsx
  src/redux/config/configStore.ts
  src/redux/modules/searchValueSlice.ts
Labels: 🎉add, 🩹 fix

#135 Feat/responsive
  src/apis/commentAlert.ts
  src/components/board/Editor.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/place_detail/PlaceDetailHeader.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewLikes.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/pages/board/write/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  src/utils/dateFormatter.ts
Labels: 🐛 bugfix

#137 [Feat/responsive] css 수정
  public/images/icons/bookmark_select.svg
  public/images/icons/bookmark_select_.svg
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/place_detail/PlaceDetailHeader.tsx
Labels: 💄 style

#139 [Feat/additional themes] 색맹모드 아이콘 제작 + 적용 + 색맹모드 디자인
  public/images/icons/CBicons/CBbasic-logo.svg
  public/images/icons/CBicons/CBbookmark_select.svg
  public/images/icons/CBicons/CBbookmark_select_.svg
  public/images/icons/CBicons/CBcomment_select.svg
  public/images/icons/CBicons/CBfilled-heart.svg
  public/images/icons/CBicons/CBmarker.svg
  public/images/icons/CBicons/CBshare_select.svg
  public/images/icons/CBicons/CBwrite_select.svg
  src/apis/comments.ts
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/common/ReviewCard2.tsx
  src/components/common/ReviewCardMobile.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/components/map/MarkerContainer.tsx
  src/components/map/MylocationOverlayMap.tsx
  src/components/map/PagiNation.tsx
  src/components/map/PlacesModal.tsx
  src/components/place_detail/PlaceDetailHeader.tsx
  src/components/review_details/CommentInput.tsx
  src/components/review_details/ReviewLikes.tsx
  src/hooks/useBookmarks.ts
  src/pages/place/[placeId]/index.tsx
  src/pages/review/[reviewId]/index.tsx
  tailwind.config.ts
Labels: 🎉add, 💄 style

#140 [Feat/additional themes] 일부 디자인 수정
  public/images/icons/CBicons/CBbookmark.svg
  public/images/icons/bookmark.svg
  src/components/place_detail/PlaceDetailHeader.tsx
  src/pages/404.tsx
Labels: 🎉add, 💄 style

#141 [Feat/places] 리뷰 삭제시 스토리지에 있는 이미지도 지우도록 수정
  src/apis/reviews.ts
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard2.tsx
  src/components/common/PlaceCard3.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/map/MarkerContainer.tsx
  src/components/mypage/MyTabs.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/places/index.tsx
Labels: 🐛 bugfix, 🎉add, 💄 style

#142 Feat/main page search nearby버튼사이즈 수정, 지도 확대수준 수정, wheelable false로 수정
  src/components/map/PlacesModal.tsx
  src/pages/nearby/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
Labels: 🩹 fix

#143 [Feat/places] 장소카드 모바일사이즈 수정
  src/components/common/PlaceCard.tsx
Labels: 💄 style

#144 ]Feat/responsive] baseurl 수정
  src/apis/commentAlert.ts
  src/components/review_details/ReviewLikes.tsx
  src/utils/shareKaKao.ts
Labels: 🩹 fix

#145 fix:상세페이지 지도 크기 축소 근처페이지 페이지네이션 버튼위치 조절
  src/components/map/PagiNation.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🩹 fix

#146 ]Feat/responsive] default img 수정 (임시)
  next.config.js
  src/components/common/Carousel.tsx
  src/components/common/Carousel_Thumb.tsx
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard2.tsx
  src/components/common/PlaceCard3.tsx
  src/pages/index.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 🩹 fix

#147 fix:오버레이 클릭시 페이지 이동안하고 닫히는 문제해결
  src/components/map/MarkerContainer.tsx
Labels: 🩹 fix

#148 [Feat/places] 사이드바 닫히게 수정
  src/components/layout/SideBar.tsx
  src/pages/index.tsx
Labels: 🐛 bugfix, 💄 style

#149 [Feat/additional themes] 사이드바 theme 별 색상 적용
  src/components/layout/SideBar.tsx
Labels: 💄 style

#151 [Feat/places] 리뷰 삭제할 때 리뷰 이미지에 장소 대표이미지가 포함된 경우 스토리지에 삭제되지 않도록 수정
  src/apis/reviews.ts
  src/components/review_details/ReviewUpperSection.tsx
  src/types/supabase.d.ts
  src/types/types.d.ts
Labels: 🐛 bugfix

#152 [Feat/additional themes] 이전 theme 기억했다가 그걸 자동으로 적용하도록 설정
  package.json
  src/apis/places.ts
  src/components/layout/ThemeSwitcher.tsx
  src/components/map/PlacesModal.tsx
  src/pages/providers.tsx
  yarn.lock
Labels: 🐛 bugfix, 🩹 fix

#153 [Feat/additional themes] 장소 시설 아이콘 추가 및 placedetail 에 적용
  public/images/icons/place_icons/안내견동반_black.svg
  public/images/icons/place_icons/안내견동반_white.svg
  public/images/icons/place_icons/오디오가이드_black.svg
  public/images/icons/place_icons/오디오가이드_white.svg
  public/images/icons/place_icons/입장료_black.svg
  public/images/icons/place_icons/입장료_white.svg
  public/images/icons/place_icons/장애인주차장_black.svg
  public/images/icons/place_icons/장애인주차장_white.svg
  public/images/icons/place_icons/장애인출입문_black.svg
  public/images/icons/place_icons/장애인출입문_white.svg
  public/images/icons/place_icons/장애인화장실_black.svg
  public/images/icons/place_icons/장애인화장실_white.svg
  public/images/icons/place_icons/점자안내_black.svg
  public/images/icons/place_icons/점자안내_white.svg
  public/images/icons/place_icons/휠체어대여가능_black.svg
  public/images/icons/place_icons/휠체어대여가능_white.svg
  src/components/place_detail/PlaceDetail.tsx
Labels: 🎉add, 💄 style

#154 Feat/main page search nearby페이지 아이콘 넣기 완료
  src/components/map/MapPlaceCard.tsx
Labels: 💄 style

#155 fix:nearby 아이콘 깨짐 수정
  src/components/map/MapPlaceCard.tsx
Labels: 🩹 fix

#158 ]Feat/responsive] placeCard 레이아웃 깨지는 문제 수정
  src/components/board/Editor.tsx
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard3.tsx
  src/components/home/MostReviews.tsx
  src/components/mypage/MyTabs.tsx
  src/pages/places/index.tsx
  src/pages/user/[userId]/index.tsx
Labels: 🩹 fix, 💄 style

#159 [Feat/image compression] 큰 사진이 업로드 되어서 자동으로 1mb 이하로 압축 기능 추가
  package.json
  src/components/mypage/MyTabs.tsx
  src/pages/review/write/[placeId]/index.tsx
  yarn.lock
Labels: 🩹 fix, 🔨 script, ✨ update

#163 [Feat/theme] 일부 theme 관련 스타일 변경
  src/components/common/PlaceCard2.tsx
  src/components/layout/ThemeSwitcher.tsx
  src/components/place_detail/PlaceDetail.tsx
Labels: 💄 style

#164 fix : 캐러셀 화살표 theme 수정 & env 변경(#104)
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/styles/globals.css
  src/utils/shareKaKao.ts
Labels: 🩹 fix

#165 fix : env 적용(#104)
  src/utils/shareKaKao.ts
Labels: 🩹 fix

#168 add : 리뷰 제출시 보여줄 스피너 (#167)
  src/components/review_write/ReviewSubmitSpinner.tsx
  src/pages/review/write/[placeId]/index.tsx
Labels: 🎉add

#172 Feat/main page search 로드맵에서 로드뷰로 이름 수정,places페이지에서 로드뷰 오버레이추가
  public/images/icons/button_내주변장소.svg
  src/components/map/PlacesModal.tsx
  src/pages/place/[placeId]/index.tsx
Labels: ✨ update

#173 [Feat/places] 디폴트 이미지 추가 및 엑박 뜨던거 수정 + 홈페이지 추가
  public/favicon.ico
  public/images/default_image.png
  public/images/default_image2.png
  src/components/common/PlaceCard.tsx
  src/components/common/PlaceCard2.tsx
  src/components/common/PlaceCard3.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyProfile.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/components/review_details/ReviewUpperSection.tsx
  src/pages/place/[placeId]/index.tsx
  src/types/supabase.d.ts
Labels: 🎉add, 💄 style

#174 Feat/main page search nearby페이지 버튼 이미지 추가
  public/images/icons/button_내주변장소.svg
  public/images/icons/button_내주변장소_오.svg
  public/images/icons/button_내주변장소_왼.svg
  src/components/map/PlacesModal.tsx
  src/pages/place/[placeId]/index.tsx
Labels: 💄 style

#179 [Feat/responsive] 캐러셀 화살표 변경 및 자잘한 수정
  public/images/icons/button/next.svg
  public/images/icons/button/prev.svg
  src/components/board/Editor.tsx
  src/components/home/MostBookmarks.tsx
  src/components/home/MostReviews.tsx
  src/components/place_detail/PlaceDetail.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/place/[placeId]/index.tsx
  src/styles/globals.css
Labels: 🩹 fix, 💄 style

#180 Feat/main page search 장소검색 필터링 수정,로드뷰 스타일추가
  src/components/map/MarkerContainer.tsx
  src/components/map/MylocationOverlayMap.tsx
  src/pages/place/[placeId]/index.tsx
  src/pages/places/index.tsx
Labels: 🩹 fix, 💄 style

#181 [Feat/fixsearch] 무한스크롤 useInfiniteQuery로 리팩토링!!
  src/apis/places.ts
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/pages/places/index.tsx
Labels: ♻️ refactor

#182 [Feat/places] 불필요한 코드 정리 및 비번찾기페이지 스타일 수정
  src/apis/places.ts
  src/pages/login/index.tsx
  src/pages/places/index.tsx
  src/pages/update-password/index.tsx
Labels: 🚚 move, 💄 style
